name: Auto-Fix from Issues

on:
  issues:
    types: [opened, labeled]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to process'
        required: true
        type: string

jobs:
  analyze-and-fix:
    runs-on: ubuntu-latest
    # Only run if issue has 'auto-fix' label or was created by bot
    if: |
      contains(github.event.issue.labels.*.name, 'auto-fix') ||
      github.event.issue.user.type == 'Bot' ||
      github.event_name == 'workflow_dispatch'
    
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write  # Required for AWS Bedrock OIDC authentication
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better code analysis
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          # Note: cache removed because service repos don't have requirements.txt
      
      - name: Install Issue Agent
        run: |
          git clone https://github.com/parimalpate123/issue-fix-action.git /tmp/issue-fix-action
          cd /tmp/issue-fix-action
          pip install -r requirements.txt
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}
      
      - name: Run Issue Agent
        env:
          BEDROCK_MODEL_ID: ${{ secrets.BEDROCK_MODEL_ID || 'anthropic.claude-3-5-sonnet-20240620-v1:0' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number || github.event.inputs.issue_number }}
          REPOSITORY: ${{ github.repository }}
        run: |
          python /tmp/issue-fix-action/src/agents/issue_agent.py \
            --issue-number $ISSUE_NUMBER \
            --repo $REPOSITORY \
            --output-dir ./agent-output
      
      - name: Notify webhook
        if: success() && hashFiles('agent-output/pr_result.json') != ''
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        run: |
          # Extract incident_id from issue body
          INCIDENT_ID=$(python3 << 'PYTHON_EOF'
          import json
          import re
          import sys
          
          try:
              with open('agent-output/analysis.json', 'r') as f:
                  data = json.load(f)
                  issue_body = data.get('issue', {}).get('body', '')
                  
                  # Try to extract from issue body (format: "Incident: chat-xxx" or "Incident ID: chat-xxx")
                  match = re.search(r'Incident(?: ID)?:\s*([a-z0-9-]+)', issue_body, re.IGNORECASE)
                  if match:
                      print(match.group(1))
                      sys.exit(0)
          except Exception as e:
              print(f"Error: {e}", file=sys.stderr)
          
          sys.exit(1)
          PYTHON_EOF
          )
          
          if [ -n "$INCIDENT_ID" ]; then
            PR_NUMBER=$(python3 -c "import json; f=open('agent-output/pr_result.json'); d=json.load(f); print(d.get('pr_number', ''))" 2>/dev/null || echo "")
            PR_URL=$(python3 -c "import json; f=open('agent-output/pr_result.json'); d=json.load(f); print(d.get('pr_url', ''))" 2>/dev/null || echo "")
            ISSUE_NUMBER=${{ github.event.issue.number || github.event.inputs.issue_number }}
            
            echo "Notifying webhook for incident: $INCIDENT_ID, PR: $PR_NUMBER"
            
            curl -X POST "$WEBHOOK_URL" \
              -H "Content-Type: application/json" \
              -H "X-Webhook-Token: $WEBHOOK_SECRET" \
              -d "{
                \"action\": \"remediation_webhook\",
                \"source\": \"github_actions\",
                \"incident_id\": \"$INCIDENT_ID\",
                \"issue_number\": $ISSUE_NUMBER,
                \"pr_number\": $PR_NUMBER,
                \"pr_url\": \"$PR_URL\",
                \"status\": \"pr_created\"
              }" || echo "Webhook call failed (non-critical)"
          else
            echo "Warning: Could not extract incident_id from issue body, skipping webhook notification"
            echo "Issue body preview:"
            python3 -c "import json; f=open('agent-output/analysis.json'); d=json.load(f); print(d.get('issue', {}).get('body', '')[:200])" 2>/dev/null || echo "Could not read issue body"
          fi
      
      - name: Comment on issue
        if: always() && hashFiles('agent-output/analysis.json') != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if update_issue_comment.py exists before running
          if [ -f "/tmp/issue-fix-action/src/utils/update_issue_comment.py" ]; then
            python /tmp/issue-fix-action/src/utils/update_issue_comment.py \
              --issue-number ${{ github.event.issue.number || github.event.inputs.issue_number }} \
              --repo ${{ github.repository }} \
              --status-dir ./agent-output
          else
            echo "update_issue_comment.py not found, skipping issue comment update"
          fi
      
      - name: Upload agent logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: issue-agent-logs-${{ github.event.issue.number || github.event.inputs.issue_number }}
          path: |
            agent-output/
            *.log
          retention-days: 7