#!/bin/bash
# Test PR Review Agent workflow

set -e

REPO_NAME="poc-payment-service"
GITHUB_ORG="${GITHUB_ORG:-parimalpate123}"

echo "🧪 Testing PR Review Agent Workflow"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📋 Checklist:"
echo ""
echo "1. ✅ Workflow file deployed: .github/workflows/pr-review.yml"
echo "2. ⏳ Secrets configured in GitHub:"
echo "   - WEBHOOK_URL"
echo "   - WEBHOOK_SECRET"
echo "   - AWS_ACCESS_KEY_ID"
echo "   - AWS_SECRET_ACCESS_KEY"
echo "   - AWS_REGION (optional)"
echo "   - BEDROCK_MODEL_ID (optional)"
echo "   - PAT_TOKEN (optional)"
echo ""
echo "3. ⏳ Test the workflow:"
echo ""

echo "🔍 To verify the workflow is set up correctly:"
echo ""
echo "   Option A: Check existing PRs"
echo "   1. Go to: https://github.com/${GITHUB_ORG}/${REPO_NAME}/pulls"
echo "   2. Find a PR created by Issue Agent (should have 'auto-fix' label on linked issue)"
echo "   3. Check Actions tab: https://github.com/${GITHUB_ORG}/${REPO_NAME}/actions"
echo "   4. Look for 'PR Review Agent' workflow runs"
echo ""

echo "   Option B: Manual trigger (for testing)"
echo "   1. Go to: https://github.com/${GITHUB_ORG}/${REPO_NAME}/actions/workflows/pr-review.yml"
echo "   2. Click 'Run workflow'"
echo "   3. Enter a PR number that has an incident ID"
echo "   4. Click 'Run workflow' button"
echo ""

echo "   Option C: Create a test PR"
echo "   1. Create a new PR with 'Incident: chat-1234567890-test' in the body"
echo "   2. Link it to an issue with 'auto-fix' label"
echo "   3. The workflow should trigger automatically"
echo ""

echo "🔍 To debug if workflow isn't triggering:"
echo ""
echo "1. Check workflow file exists:"
echo "   https://github.com/${GITHUB_ORG}/${REPO_NAME}/blob/main/.github/workflows/pr-review.yml"
echo ""
echo "2. Check if workflow appears in Actions:"
echo "   https://github.com/${GITHUB_ORG}/${REPO_NAME}/actions"
echo "   (Should see 'PR Review Agent' in the left sidebar)"
echo ""
echo "3. Check workflow syntax:"
echo "   GitHub should show any YAML syntax errors in the Actions tab"
echo ""
echo "4. Check if PR has required data:"
echo "   - PR body contains 'Incident:' or 'Incident ID:'"
echo "   - OR linked issue has 'auto-fix' label"
echo "   - Linked issue body contains 'Incident:' or 'Incident ID:'"
echo ""

echo "🔍 To debug if workflow runs but fails:"
echo ""
echo "1. Go to the workflow run in Actions tab"
echo "2. Check the 'Extract PR number and incident ID' step:"
echo "   - Should show extracted incident_id"
echo "   - If empty, check PR/issue body format"
echo "3. Check the 'Notify webhook' steps:"
echo "   - Should show webhook calls (may fail silently with 2>/dev/null)"
echo "4. Check the 'Run PR Review Agent' step:"
echo "   - Should show the review action running"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📝 Quick Test Steps:"
echo ""
echo "1. Open: https://github.com/${GITHUB_ORG}/${REPO_NAME}/actions/workflows/pr-review.yml"
echo "2. Click 'Run workflow' → 'Run workflow' (with a test PR number)"
echo "3. Watch the workflow run"
echo "4. Check logs in each step"
echo ""
